
Harness Error (TIMEOUT), message = null

FAIL piping should not be observable promise_test: Unhandled rejection with value: object "TypeError: |this| is not a Promise"
FAIL tee should not be observable promise_test: Unhandled rejection with value: object "TypeError: |this| is not a Promise"

