
PASS # AUDIT TASK RUNNER STARTED. 
PASS Executing "test" 
PASS Audit report 
PASS > [test] Test setValueAtTime with startTime in the past 
FAIL X Test[0:127]: Expected 1 for all values but found 128 unexpected values: 
	Index	Actual
	[0]	63.7490234375
	[1]	64.74510192871094
	[2]	65.74118041992188
	[3]	66.73725891113281
	...and 124 more errors. assert_true: expected true got false
FAIL X Reference[0:127]: Expected 1 for all values but found 127 unexpected values: 
	Index	Actual
	[0]	0
	[2]	2
	[3]	3
	[4]	4
	...and 123 more errors. assert_true: expected true got false
FAIL X Test[128:] expected to be equal to the array [128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143...] but differs in 16128 places:
	Index	Actual			Expected
	[0]	1.9124707031250000e+2	1.2800000000000000e+2
	[1]	1.9224314880371094e+2	1.2900000000000000e+2
	[2]	1.9323922729492188e+2	1.3000000000000000e+2
	[3]	1.9423530578613281e+2	1.3100000000000000e+2
	...and 16124 more errors. assert_true: expected true got false
FAIL < [test] 3 out of 3 assertions were failed. assert_true: expected true got false
FAIL # AUDIT TASK RUNNER FINISHED: 1 out of 1 tasks were failed. assert_true: expected true got false

